### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by haseebzeeshan2010** [Quaint-Studios/Reia#19]
Hi, I found out about this project today and really wanted to try it out(and perhaps contribute later on), but found it unclear how to install on Linux - I am using Ubuntu 22.04 LTS.

Please correct me if I am missing something, I would really appreciate if you could help.

**Comment by Makosai** [comment]
Hi, @haseebzeeshan2010! Thanks for taking an interest in Reia.

There currently isn't an automated build for Linux. I'll be able to make one either tomorrow or sometime Monday for you. But, if you have Godot installed already then you can build and test it right now from https://github.com/Quaint-Studios/Reia/tree/v1.0.0.5-pre-alpha or the master branch.

Once I have some more time to work on the rest of the pre-alpha roadmap, I'll eventually make documentation on project structures, how to build, and where to find downloads.

Let me know if you have any more questions in the meantime.

**Comment by haseebzeeshan2010** [comment]
Thanks for the reply. I tried it and it works perfectly.

**Comment by Makosai** [comment]
Awesome! I'll look into still making an automated build for the future.
